wrapping the zarf wrapper

diff --git a/packages/keycloak-config-wrapper/zarfception.yaml b/packages/keycloak-config-wrapper/zarfception.yaml
--- a/packages/keycloak-config-wrapper/zarfception.yaml
+++ b/packages/keycloak-config-wrapper/zarfception.yaml
@@ -1,3 +1,4 @@
+# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/main/zarf.schema.json
 kind: ZarfPackageConfig
 metadata:
   name: keycloak-config-wrapper
@@ -6,21 +7,38 @@ metadata:
 components:
   - name: keycloak-config-wrapper
     required: true
-    description: Loads jar files at deploy time into a new zarf package
+    description: Loads a local jar file into the cluster via zarf data injection.
     only:
       cluster:
         architecture: amd64
-    files:
-      # Transfer the files for zarf to use at deploytime
-      - source: init-job.yaml
-        target: tmp_deploy/init-job.yaml
-      - source: zarfception.yaml
-        target: tmp_deploy/zarf.yaml
+    manifests:
+      #create a job from the pre-existing init image
+      - name: data-loader
+        namespace: keycloak
+        files: 
+          - init-job.yaml
+    dataInjections:
+      - source: tmp_deploy
+        target:
+          namespace: keycloak
+          selector: app=data-loader
+          container: uds-config-loader
+          path: /home/nonroot
+        compress: false
+    images:
+      - ghcr.io/defenseunicorns/uds/identity-config:0.3.6
     actions:
-      onDeploy:
+      onCreate:
         before:
           # cleanup output from previous attempts
           - cmd: |
+              rm -rf tmp_deploy
+              mkdir tmp_deploy
+      onDeploy:
+        before:
+          # cleanup previous attempts
+          - cmd: |
+              ./zarf tools kubectl delete job -n keycloak identity-config-loader 2>/dev/null || true
               rm -rf tmp_deploy
               mkdir tmp_deploy
           
@@ -28,24 +46,17 @@ components:
           - cmd: if [ "$(uname -m)" != "x86_64" ]; then echo "this package architecture is amd64, but the target system has a different architecture. These architectures must be the same" && exit 1; fi
             description: Check that the host architecture matches the package architecture
             maxRetries: 0
-        after:
-          # check for jar files (CAN EXIT EARLY)
+
+          # check if any jars exist
           - cmd: |
               COUNT=`ls -1 *.jar 2>/dev/null | wc -l`
               if [ $COUNT = 0 ]; then 
                 echo "No local JAR files detected -- SKIPPING CUSTOM PLUGIN LOAD"
                 exit 0
-              fi 
-
-              # move to workdir
+              fi
+              
+              # populate the workdir
               cp *.jar tmp_deploy/
-              cd tmp_deploy
-
-              # build the zarf wrapper wrapper (yo dawg... 'zarfception.yaml') -- collect the local files
-              ./zarf package create . --confirm
-
-              # deploy the zarf wrapper
-              ./zarf package deploy zarf-package*.tar.zst --confirm 
         
         # CLEANUP attempted deploys
         onSuccess:
